apiVersion: apps/v1
kind: Deployment
metadata:
  name: productorder-k8s
spec:
  selector:
    matchLabels:
      app: productorder-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: productorder-k8s
    spec:
      containers:
        - name: productorder-k8s
          image: 19990106/ctse-productorder-k8s:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 50Mi
              cpu: 80m
            limits:
              memory: 100Mi
              cpu: 120m
          ports:
            - containerPort: 3000
          
    