apiVersion: apps/v1
kind: Deployment
metadata:
  name: userbackend-k8s
spec:
  selector:
    matchLabels:
      app: userbackend-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: productOrder-k8s
    spec:
      containers:
        - name: productOrder-k8s
          image: 19990106/ctse-productOrder-k8s:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      tolerations:
        - key: "key"
          operator: "Exists"
          effect: "NoSchedule"